import requests
from bs4 import BeautifulSoup
import json

print("Fetching live constituency data from Wikipedia (V2 Engine)...")

url = "https://en.wikipedia.org/wiki/List_of_constituencies_of_the_Lok_Sabha"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

state_map = {}

# Step 1: Find all data tables on the page directly
tables = soup.find_all('table', class_='wikitable')

for table in tables:
    # Check if this table actually holds constituency names (looks for 'Name' in headers)
    headers = [th.text.strip() for th in table.find_all('th')]
    
    if 'Name' in headers or 'Constituency' in headers:
        # Step 2: Look backwards to find the nearest State heading
        prev_heading = table.find_previous(['h2', 'h3'])
        
        if prev_heading and prev_heading.find('span', class_='mw-headline'):
            # Clean up the state name (e.g., changes "Andhra Pradesh (25)" to "Andhra Pradesh")
            state_name = prev_heading.find('span', class_='mw-headline').text.split('(')[0].strip()
            
            constituencies = []
            
            # Step 3: Extract the names from the 2nd column
            for row in table.find_all('tr')[1:]:
                cols = row.find_all(['td', 'th'])
                if len(cols) >= 2:
                    name = cols[1].text.strip()
                    # Clean up random Wikipedia footnotes like "Name[a]"
                    name = name.split('[')[0].strip() 
                    
                    if name and name != "Name":
                        constituencies.append(name)
            
            # Save it to our dictionary (ignoring the 'Summary' table)
            if constituencies and state_name != "Summary":
                state_map[state_name] = constituencies

total_seats = sum(len(v) for v in state_map.values())
print(f"Successfully scraped {total_seats} constituencies across {len(state_map)} States/UTs!")

# Automatically write this data into your Python file
with open('constituencies.py', 'w', encoding='utf-8') as f:
    f.write("# Auto-generated by build_data.py\n")
    f.write("STATE_CONSTITUENCY_MAP = " + json.dumps(state_map, indent=4, ensure_ascii=False))

print("Saved perfectly to constituencies.py!")